### ISSUE TITLE
Epic : End to end Tests

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#234]
This epic lists the end to end tests.
- [x] #235
   - (passing) [000.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/000.sh) setup through mgmt, mgmt-staging repos Ready
- [x] #236 
   - (passing) [001.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/001.sh) regional
   - (passing) [002.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/002.sh) edge
- [x] #237
   - (passing) [004.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/004.sh) provision operator on all workload clusters
- [x] #238 
   - [x] (passing) [003.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/003.sh) free5gc-cp
   - [ ] (failing) [005.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/005.sh) AMF, SMF
   - [ ] (failing) [006.sh](https://github.com/nephio-project/test-infra/blob/main/e2e/tests/006.sh) UPF
- [x] (stretch) #150
   - (to be written) 007.sh assign to @denysaleksandrov 
- [x] #239
   - (to be written) 008.sh assign to @rravindran123 
- [x] #240
   - (to be written) 009.sh assigned (but not confirmed by her yet!) to @n2vo 
- [x] #241 - I don't think we have an automated way to do this
- [x] (stretch) "other NF" package(s) - make more configurable and use pkg to deploy

**Comment by johnbelamaric** [comment]
We have a framework for e2e tests to build these out.

If you look in https://github.com/nephio-project/test-infra/tree/main/e2e/tests you will see NNN.sh files. Right now, there is a [PR](https://github.com/nephio-project/test-infra/pull/70) to add up through 006.sh which would cover the first 4 of these. I will note them up above, and assign numbers to each of the others so we can not clobber each other.

**Comment by johnbelamaric** [comment]
Ok, I assigned each of these a test case number, so we can dole them out separately and people can work on them without conflicting.

I noted in each individual issue which test case number they should use.

Right now, we have everything through the operator coming up. To get a call through, we still need:
- The updated free5gc operator and operator package
- The updated SMF, AMF, UPF packages that use the entire package specialization pipeline
- The solution to populating UPF information into the SMF package
- Intercluster networking, either automatically or manually (e.g., run a script that generates a container lab topology) after provisioning the clusters

**Comment by johnbelamaric** [comment]
All done and working :)
