### ISSUE TITLE
EPIC: Integrated deployment of OAI RAN and OAI core, end to end call using UE and RF simulator

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#361]
Goals

- Define Architecture, Requirements, Intent/CRDs for RAN Deployment using Nephio. 
- Demonstrate closed loop automation using RAN operators. 
- Align with O-RAN (e.g. O-RAN Architecture, usecases, O1, O2)
- Collaborate with other Open source RAN related software like O-RAN SC, OAI etc

R2 scope

- Architecture and Requirements for R2 and beyond R2 (SIG1/WG2):
- Intent/CRDs for RAN
- Architecture, Requirements  which aligns with the O-RAN (e.g. O1, O2)
- Framework for RAN Metrics/KPI collection (O1 other mechanisms)
- Closed Loop Automation (e.g. CPU config, scaling for RAN NFs)
- Development: RAN deployment demonstration using Nephio
- Identify open source RAN NF for validations and demonstrations. e.g. OAI, ORAN SC
- Define CRD, develop RAN custom controller, perform deployment using Nephio framework and demonstrate end to end call
- Discuss further in SIG 1/WG2 if any specific CRD can be demonstrated in R2.

- [x] #362
- [x] #363
- [x] #364
- [x] #365
- [x] #366
- [x] #367
- [x] #368
- [x] #369
- [x] #370
- [x] #392

**Comment by gvbalaji** [comment]
Current status: Deployed OAI RAN (RF simulator mode with Sample CRD and hardcoded working configurations using custom k8s controller.) 
Immediate Next step

- Identify configurable parameters for RAN
- Define the CRD (identify the intent and constant parameters)
- Deploy using Nephio framework with RAN CRD
-

**Comment by arora-sagar** [comment]
@gvbalaji Can you assign this issue to me and @josephthaliath

**Comment by arora-sagar** [comment]
Me and @josephthaliath made this blueprint for R2 use case. It will be great if we can get some feedback from everyone. The cloud terminologies we have taken from `O-RAN.WG6.CADS-v4.00 TR page 23`. 

[Image](https://drive.google.com/file/d/1KVgc4ohmdocfExMG0F_9N_iBCgu9Pcep/view?usp=sharing)

**Comment by rravindran123** [comment]
@arora-sagar , that image lacks resolution, can we have an image with better resolution ?

**Comment by rravindran123** [comment]
> Goals
> 
> * Define Architecture, Requirements, Intent/CRDs for vRAN Deployment using Nephio.
> * Demonstrate closed loop automation using vRAN operators.
> * Align with O-RAN (e.g. O-RAN Architecture, usecases, O1, O2)
> * Collaborate with other Open source RAN related software like O-RAN SC, OAI etc
> 
> R2 scope
> 
> * Architecture and Requirements for R2 and beyond R2 (SIG1/WG2):
> * Intent/CRDs for RAN
> * Architecture, Requirements  which aligns with the O-RAN (e.g. O1, O2)
> * Framework for RAN Metrics/KPI collection (O1 other mechanisms)
> * Closed Loop Automation (e.g. CPU config, scaling for RAN NFs)
> * Development: RAN deployment demonstration using Nephio
> * Identify open source RAN NF for validations and demonstrations. e.g. OAI, ORAN SC
> * Define CRD, develop RAN custom controller, perform deployment using Nephio framework and demonstrate end to end call
> * Discuss further in SIG 1/WG2 if any specific CRD can be demonstrated in R2.
> * [ ]  [Define RAN CRDs + allow vendor specific extensions #362](https://github.com/nephio-project/nephio/issues/362)
> * [ ]  [Prepare Network configuration and deployment figure for integrated RAN and core deployment #363](https://github.com/nephio-project/nephio/issues/363)
> * [ ]  [OAI RAN NF custom controller #364](https://github.com/nephio-project/nephio/issues/364)
> * [ ]  [OAI RAN deployment KRM functions #365](https://github.com/nephio-project/nephio/issues/365)
> * [ ]  [OAI RAN KPT packages #366](https://github.com/nephio-project/nephio/issues/366)
> * [ ]  [OAI core deployment #367](https://github.com/nephio-project/nephio/issues/367)
> * [ ]  [OAI UE simulator KPT package #368](https://github.com/nephio-project/nephio/issues/368)
> * [ ]  [Deployment of End to End OAI RAN and OAI core #369](https://github.com/nephio-project/nephio/issues/369)
> * [ ]  [Deployment of End to End OAI RAN and free5gc [stretch] #370](https://github.com/nephio-project/nephio/issues/370)

1. Replace RAN with vRAN
2. To allign with O-RAN use cases we have allign with O-RAN Architecture, e.g. SMO has FOCOM/NFO and south end has the O-Cloud, so need an architecture with Nephio that includes these sub-components as well
3. O1 today interfaces with vRAN functions for CU/DU/RU configuration, IMO, we should just scope to O2 right now, as we are not sure how much Service aware or agnostic Nephio should be

**Comment by rravindran123** [comment]
> Me and @josephthaliath made this blueprint for the R2 use case. It will be great if we can get some feedback from everyone. The cloud terminologies we have taken from `O-RAN.WG6.CADS-v4.00 TR` document page 23.
> 
> Here are the questions I would like to ask everyone,
> 
> 1. Is the terminology for core cloud, regional cloud, and edge cloud okay?
> 2. The placement of different network functions in their respective clouds
> 3. Right now there are three clusters plus one mgmt cluster. Should we have another cluster for the UEs? It is possible but it depends if everyone would like to have it or not.
> 
> [Image](https://drive.google.com/file/d/1KVgc4ohmdocfExMG0F_9N_iBCgu9Pcep/view?usp=sharing)
> 
> To open the image I suggest you use draw.io.

1. Looking at the figure, if we want to make it O-RAN compliant from a terminology perspective, we could call the clouds running vRAN functions, as Edge O-Cloud and Regional O-Cloud, this may lead to more question on IMS/DMS etc, but I think the alignment here is only from the terminology not to the O-RAN architecture itself.
2. Also from the CU-CP placement perspective, I see it is part of the Regional, and now we have another Central Cloud for the core control functions, but why are the functions called "amf-regional" etc ?, would suggest to have the Core and CU-CP as part of the regional, and have the Central cloud to include the Nephio mgmt, that will give the complete picture.
3. Also will be good to show if the Operators are part of the Nephio or the Workload clusters.

**Comment by arora-sagar** [comment]
Hi @rravindran123 thanks for the comments. The regional one was my error since I copied that part from my R1 diagram. I corrected it. The operators will be on the workload cluster, I made that correction too.

**Comment by henderiw** [comment]
@electrocucaracha to take the E2E lead
OAI and free5gc interworking is out of scope for R2

**Comment by electrocucaracha** [comment]
The following tasks have been detected for the OAI infra deployment in test-infra project:

- [x] Create an environment variable to specify the End-to-End scenario to execute, e.g ${NEPHIO_E2E_TYPE:-free5gc} and move the existing testing scripts from e2e/tests/ to e2e/tests/free5gc and update their references. [Completed](https://github.com/nephio-project/test-infra/pull/218)
- [ ] Create new sequential bash scripts in e2e/tests/oai for End-to-End scenario. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/ba4388533a71c9c9827c00cf7cc7665700e0ad50)
- [ ] Define new Terraform variables to control and pass the End-to-End scenario to execute. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/3fb5c9ff16fffd9cf7f4cb2ef2111298ed83438e)
- [ ] Rename topology from `free5gc` to something generic. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/0ec2f0e8c168e5f7f57774aa6a5bb57d390ca648)
- [ ] Add new VLAN IDs in for i in {2..4} change it to for i in {2..6}. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/ad1e6d8bc828efbfbfff7b9c2f04ee627efcca66)
- [ ] Update the nephio-example-packages/network with new vpcs. [In Progress](https://github.com/nephio-project/catalog/pull/7)
- [ ] Update `test-infra/e2e/provision/hacks/network-topo.sh` with new cluster labels and network name. [In Progress](https://github.com/nephio-project/test-infra/pull/219/commits/ba4388533a71c9c9827c00cf7cc7665700e0ad50)

The `nephio-project\test-infra` project requires the `workloads\oai\network` kpt package of the `nephio-project\catalog` project, so this [PR](https://github.com/nephio-project/catalog/pull/7) requires to be merged first.
