### ISSUE TITLE
EPIC : Support nephio deployment on real k8s clusters

### ISSUE THREAD

**Issue by gvbalaji** [nephio-project/nephio#576]
Today we have Nephio running on the sandbox based on KIND  and we can make e2e pings for free5gc and OAI. However we can not deploy Nephio on a real k8s cluster and achieve the same.  This epic covers the issues related to supporting Nephio deployment on a real k8s and acheiving infrastructure orchestration ( cluster creation), CNF orchestration and configuration and e2e calls

- [ ] Deploy Nephio management cluster components on real k8s 
- [ ] Create real workload clusters using Nephio
- [ ] Deploy OAI RAN and Core workloads onto real k8s clusters using Nephio
- [ ] Support networking for intercluster communication for OAI workloads
- [ ] Make e2e calls with OAI RAN and Core on real k8s clusters deployed with Nephio
- [ ] Deploy free5gc Core workloads onto real k8s clusters using Nephio
- [ ] Support networking for intercluster communication for OAI workloads
- [ ] Make e2e calls with free5gc Core on real k8s cluster deployed with Nephio
